### ISSUE TITLE
USB not working

### ISSUE THREAD

**Issue by ThomasParchmann** [n00b69/woa-beryllium#5]
### Description

Hey, i just updated the drivers using the Online Updater Cmd, but the USB still doesn't work even though it should according to the status. 
Any idea where to find the working driver? 
Or is it normal that this does not work?
Edit: I already enabled USB Host Control with the exe from the troubleshoot site.

### Reproduction steps

```bash
Update the drivers using the OnlineUpdater.cmd
Plug something like a mouse with an adapter into the usb-c port.
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 on the phone
- [X] There is no issue already describing my problem.

**Comment by ThomasParchmann** [comment]
Yes, i have tried plugging it in before booting the device and after booting it, both methods didn't work.

**Comment by n00b69** [comment]
Do you have access to a powered USB hub to try?
And did you ever repair your USB port by any chance?

**Comment by ThomasParchmann** [comment]
Ah yes, i haven't thought about that. Since i bought the phone used, the hub might have been replaced. I will have a look into that, thanks!
