### ISSUE TITLE
[BUG] - Windows 11 BSODs on first boot and then refuses to do setup

### ISSUE THREAD

**Issue by Razboinicul** [n00b69/woa-beryllium#6]
### Description

When I install Windows 11 on my phone, it BSODs on first boot and then refuses to do setup(gives out a popup that says that the setup cannot continue).

### Reproduction steps

```bash
Install everything using the instructions
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 on the phone
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Have you used the firstboot.img for your paneltype?

**Comment by Razboinicul** [comment]
yes

**Comment by Razboinicul** [comment]
Now it works, I didn't follow the tutorial properly ig, not sure what I did but it works now.
