### ISSUE TITLE
[BUG] - <random BSOD 0x00000000>

### ISSUE THREAD

**Issue by RONNIE158** [n00b69/woa-beryllium#7]
### Description

Fund random bsod 0x00000000 in latest uefi.

### Reproduction steps

```bash
Fund random bsod 0x00000000 in latest uefi.
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 on the phone
- [X] There is no issue already describing my problem.

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by n00b69** [comment]
Did you just install Windows or are you using the UEFI on an existing install that worked before?

**Comment by RONNIE158** [comment]
i used uefi v2.0rc2, and using the installation from kumar jy, and running normally including rotation, after I updated the driver and the latest uefi there was a random bsod, then I replaced the bypassNRO driver from woa duo, no more random bsods anymore. maybe the problem is in the bypassNRO driver.

**Comment by RONNIE158** [comment]
btw thanks for fixing the broken touch issue after sleeping, I hope sms and calls work in the future.

**Comment by n00b69** [comment]
Sms, MAYBE. Calls, probably never.
