### ISSUE TITLE
latest driver can kill the bottom speaker

### ISSUE THREAD

**Issue by RONNIE158** [n00b69/woa-beryllium#8]
### Description

the latest driver could kill the bottom speaker, I haven't disassembled it for further investigation.

### Reproduction steps

```bash
remove audio driver temporarily
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 on the phone
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Did your speaker actually die and it no longer works even in Android?

**Comment by RONNIE158** [comment]
on Android it doesn't work, only earpeace still works

**Comment by n00b69** [comment]
Did you by any chance try to make the volume higher than what it originally was in Windows? Just trying to figure out what happened, because you're the only one who has reported this issue and the drivers have been available for a while.

**Comment by temblor55** [comment]
Dude 
Can you explain in detail what happened?
And was there any noticed issues with speaker before that ?

**Comment by RONNIE158** [comment]
The speaker of course still works on Android and Windows. one time I was watching YouTube and turned up the volume high, After a while there was a loud beep on the speaker, I tried lowering the volume but it didn't work, I tried restarting the device immediately, after up, I don't hear anything on the speakers, except the earpiece which is still working.

**Comment by RONNIE158** [comment]
I apologize for my bad English

**Comment by temblor55** [comment]
Then it still works on both Os , that's fine 

Audio driver in beryllium is not unstable, i suggest to not turn volume Higher , please keep it at 70% 
We will try to debug the audio drivers to see what causes the problems

**Comment by RONNIE158** [comment]
I have taken it to the repairman, he said that there was a component that was burnt and replaced it with a new component. Thank you for your help.

**Comment by temblor55** [comment]
Can you tell me what component that was burnt ?

**Comment by RONNIE158** [comment]
I think it's some kind of small capacitor and a small IC, I'm not sure because of my lack of knowledge about it.

**Comment by temblor55** [comment]
Please join us on telegram group for better communication

https://t.me/WinOnF1

**Comment by RONNIE158** [comment]
Unfortunately, Telegram is blocked in my country for some unknown reason.

**Comment by n00b69** [comment]
Closing because it got "fixed" by downgrading the AudFilter driver
