### ISSUE TITLE
[QUESTION] - The touchscreen Issue still exists yet it was removed from the Project Status ?

### ISSUE THREAD

**Issue by lalit22km** [n00b69/woa-beryllium#9]
### Question

Did I do something wrong while installing ?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by Kumar-Jy** [comment]
Have you flashed new uefi after completing window setup ?

https://github.com/Kumar-Jy/Windows-in-PocoF1-Without-PC/releases/tag/UEFI-Boot-Image

**Comment by n00b69** [comment]
Closing assuming it got fixed
